### ISSUE TITLE
Doesn't work with v1.0 of Dropwizard

### ISSUE THREAD

**Issue by darrenhaken** [dc-square/dropwizard-papertrail#1]
I tried converting the code to work with Dropwizard 1.x but its simply not pushing logs to Papertrail. Can you help?

**Comment by dobermai** [comment]
Hi Darren,

we unfortunately don't use Papertrail anymore for Dropwizard applications, so it's unlikely this plugin gets upgraded to DW 1.0. Maybe updating the Papertrail dependency to an newer version can help?
- Dominik

**Comment by thesmith** [comment]
I've created #2 to solve this. Are you happy to merge, release and continue supporting?

**Comment by dobermai** [comment]
Thanks @thesmith for the PR! I just merged it. We do not use this plugin ourselves anymore but I hope it is still useful for other folks :-)

**Comment by thesmith** [comment]
Great, thanks for that @dobermai. Any chance you could cut a new release for this?

**Comment by dobermai** [comment]
@thesmith: Sure, just released it on Maven central as version 1.2. Should be available in a few hours.

**Comment by thesmith** [comment]
You're a gentleman.
